services:
  canal-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: ebene_patrimoine_app
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - ebene_patrimoine_network

networks:
  ebene_patrimoine_network:
    driver: bridge
